### ISSUE TITLE
api OFF

### ISSUE THREAD

**Issue by erivandosena** [2016rshah/githubchart-api#34] opened 2023-07-17 11:15 UTC
http://ghchart.rshah.org/* is down

**Comment by scottwmaxwell** [comment] 2023-07-17 15:34
I think this is probably a duplicate of issue #33.

**Comment by 2016rshah** [comment] 2023-07-20 07:06
Fixed by https://github.com/2016rshah/githubchart-api/commit/639b3ff4570126d128c287a53ab79c652f012072

**Closed as completed by 2016rshah** 2023-07-20 07:06 UTC
